#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# setup.sh — Project environment setup for macOS
# Installs: uv, Python dependencies (ruff, sqlfluff, dbt-core, etc.)
# Configures: dbt profiles.yml, runs dbt deps
# =============================================================================

# --- Colours -----------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Colour

# --- Helpers -----------------------------------------------------------------
info()    { echo -e "${BLUE}[info]${NC}  $*"; }
success() { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC}  $*"; }
error()   { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }
step()    { echo -e "\n${BOLD}==> $*${NC}"; }

# --- Config ------------------------------------------------------------------
DBT_PROJECT_DIR="monorepo_dbt_demo"           # adjust if different
DBT_PROFILES_DIR="${HOME}/.dbt"
DBT_PROFILES_FILE="${DBT_PROFILES_DIR}/profiles.yml"
PROFILES_TEMPLATE_FILE="profiles.yml.example" # optional: commit this to repo

# =============================================================================
# 1. Guard: macOS only
# =============================================================================
step "Checking OS"
if [[ "$(uname)" != "Darwin" ]]; then
  error "This script is intended for macOS only. Got: $(uname)"
fi
success "macOS detected"

# =============================================================================
# 2. Install uv (if not already installed)
# =============================================================================
step "Checking uv"
if command -v uv &>/dev/null; then
  success "uv already installed: $(uv --version)"
else
  info "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh

  # Make uv available in the current shell session
  export PATH="${HOME}/.cargo/bin:${PATH}"
  export PATH="${HOME}/.local/bin:${PATH}"

  if ! command -v uv &>/dev/null; then
    error "uv installation failed or not on PATH. Try opening a new terminal and re-running."
  fi
  success "uv installed: $(uv --version)"
fi

# =============================================================================
# 3. Sync Python dependencies via uv
# =============================================================================
step "Syncing Python dependencies with uv"
uv sync
success "Dependencies synced into .venv"

# =============================================================================
# 4. Set up dbt profiles.yml
# =============================================================================
step "Configuring dbt profiles.yml"

mkdir -p "${DBT_PROFILES_DIR}"

if [[ -f "${DBT_PROFILES_FILE}" ]]; then
  warn "profiles.yml already exists at ${DBT_PROFILES_FILE} — skipping."
  warn "Delete it and re-run this script if you want to regenerate it."
else
  # If a committed template exists in the repo, copy and prompt for values
  if [[ -f "${PROFILES_TEMPLATE_FILE}" ]]; then
    info "Found ${PROFILES_TEMPLATE_FILE} — copying to ${DBT_PROFILES_FILE}"
    cp "${PROFILES_TEMPLATE_FILE}" "${DBT_PROFILES_FILE}"
    success "Copied template to ${DBT_PROFILES_FILE}"
    warn "Open ${DBT_PROFILES_FILE} and fill in your warehouse credentials."
  else
    # No template found — write a sensible default and prompt the user
    info "No ${PROFILES_TEMPLATE_FILE} found — generating a default profiles.yml"

    # Prompt for the most common fields
    echo ""
    read -rp "  Warehouse type (bigquery / snowflake / postgres / redshift) [bigquery]: " warehouse
    warehouse="${warehouse:-bigquery}"

    read -rp "  dbt profile name (must match profile: in dbt_project.yml) [default]: " profile_name
    profile_name="${profile_name:-default}"

    case "${warehouse}" in
      bigquery)
        cat > "${DBT_PROFILES_FILE}" <<EOF
# dbt profiles.yml — generated by setup.sh
# Docs: https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup

${profile_name}:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth                  # or service-account
      project: YOUR_GCP_PROJECT_ID
      dataset: YOUR_DEV_DATASET
      threads: 4
      timeout_seconds: 300
      location: US                   # e.g. US, EU, australia-southeast1
      # If using service-account, uncomment below:
      # method: service-account
      # keyfile: /path/to/keyfile.json
    prod:
      type: bigquery
      method: oauth
      project: YOUR_GCP_PROJECT_ID
      dataset: YOUR_PROD_DATASET
      threads: 8
      timeout_seconds: 300
      location: US
EOF
        ;;
      snowflake)
        cat > "${DBT_PROFILES_FILE}" <<EOF
# dbt profiles.yml — generated by setup.sh
# Docs: https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup

${profile_name}:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: YOUR_ACCOUNT          # e.g. xy12345.us-east-1
      user: YOUR_USER
      password: YOUR_PASSWORD        # or use authenticator: externalbrowser
      role: YOUR_ROLE
      warehouse: YOUR_WAREHOUSE
      database: YOUR_DATABASE
      schema: YOUR_DEV_SCHEMA
      threads: 4
    prod:
      type: snowflake
      account: YOUR_ACCOUNT
      user: YOUR_USER
      password: YOUR_PASSWORD
      role: YOUR_ROLE
      warehouse: YOUR_WAREHOUSE
      database: YOUR_DATABASE
      schema: YOUR_PROD_SCHEMA
      threads: 8
EOF
        ;;
      postgres)
        cat > "${DBT_PROFILES_FILE}" <<EOF
# dbt profiles.yml — generated by setup.sh
# Docs: https://docs.getdbt.com/docs/core/connect-data-platform/postgres-setup

${profile_name}:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: YOUR_USER
      password: YOUR_PASSWORD
      port: 5432
      dbname: YOUR_DATABASE
      schema: YOUR_DEV_SCHEMA
      threads: 4
    prod:
      type: postgres
      host: YOUR_PROD_HOST
      user: YOUR_USER
      password: YOUR_PASSWORD
      port: 5432
      dbname: YOUR_DATABASE
      schema: YOUR_PROD_SCHEMA
      threads: 8
EOF
        ;;
      redshift)
        cat > "${DBT_PROFILES_FILE}" <<EOF
# dbt profiles.yml — generated by setup.sh
# Docs: https://docs.getdbt.com/docs/core/connect-data-platform/redshift-setup

${profile_name}:
  target: dev
  outputs:
    dev:
      type: redshift
      host: YOUR_REDSHIFT_HOST.redshift.amazonaws.com
      user: YOUR_USER
      password: YOUR_PASSWORD
      port: 5439
      dbname: YOUR_DATABASE
      schema: YOUR_DEV_SCHEMA
      threads: 4
    prod:
      type: redshift
      host: YOUR_REDSHIFT_HOST.redshift.amazonaws.com
      user: YOUR_USER
      password: YOUR_PASSWORD
      port: 5439
      dbname: YOUR_DATABASE
      schema: YOUR_PROD_SCHEMA
      threads: 8
EOF
        ;;
      *)
        error "Unknown warehouse type: ${warehouse}. Supported: bigquery, snowflake, postgres, redshift"
        ;;
    esac

    success "Created ${DBT_PROFILES_FILE}"
    warn "Open ${DBT_PROFILES_FILE} and replace placeholder values with your credentials."
  fi
fi

# =============================================================================
# 5. Run dbt deps
# =============================================================================
step "Installing dbt packages (dbt deps)"

if [[ ! -d "${DBT_PROJECT_DIR}" ]]; then
  error "dbt project directory '${DBT_PROJECT_DIR}' not found. Check DBT_PROJECT_DIR in this script."
fi

cd "${DBT_PROJECT_DIR}"
uv run dbt deps
cd - > /dev/null

success "dbt packages installed"

# =============================================================================
# Done
# =============================================================================
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo "  Next steps:"
echo "  1. Edit ${DBT_PROFILES_FILE} and fill in your warehouse credentials"
echo "  2. Activate the venv:  source .venv/bin/activate"
echo "     Or prefix commands: uv run dbt run"
echo "  3. Verify dbt connection: uv run dbt debug --project-dir ${DBT_PROJECT_DIR}"
echo ""