version: 2

seeds:
  - name: JL__product_class_map
    config:
      column_types:
        col_1: varchar(2)
        col2: float
  - name: Material__rd_material_portal
    config:
      column_types:
        col_1: varchar(2)
        col2: float