
version: 2

models:
  - name: SQL_model_example
    description: 'this is a example model using SQL'
    columns:
      - name: column1
        description: 'this is a column'
        data_tests:
          - unique
          - not_null
          - is_even

  - name: python_model_example
    description: 'this is a example model using python'
    columns:
      - name: column1
        description: 'this is a column'
        data_tests:
          - unique
          - not_null
          - is_even